DROP DATABASE IF EXISTS wildnews;
CREATE DATABASE wildnews;
CREATE USER IF NOT EXISTS 'server'@'localhost';
GRANT ALL PRIVILEGES ON wildnews.* To 'server'@'localhost' IDENTIFIED BY 'mysql';

USE wildnews;

CREATE TABLE category (
	id INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(50) NOT NULL,
	description TEXT NOT NULL,
	imageURL VARCHAR(2083) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE KEY (title)
) ENGINE=INNODB;

CREATE TABLE user (
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	imageURL VARCHAR(2083),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	deletedAt TIMESTAMP NULL,
	PRIMARY KEY (id),
	UNIQUE KEY (email, username)
) ENGINE=INNODB;

CREATE TABLE post (
	id INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(250),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	deletedAt TIMESTAMP NULL,
	description TEXT,
	imageURL VARCHAR(2083),
	sourceURL TEXT,
	category INT NOT NULL,
	author VARCHAR(100) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (category)		
		REFERENCES category(id)
) ENGINE=INNODB;

CREATE TABLE comment (
	id INT NOT NULL AUTO_INCREMENT,
	author VARCHAR(100) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	deletedAt TIMESTAMP NULL,
	content TEXT,
	post INT NOT NULL,
	FOREIGN KEY (post)
		REFERENCES post(id)
) ENGINE=INNODB;

CREATE TABLE favposts (
	userId INT NOT NULL,
	postId INT NOT NULL,
	FOREIGN KEY (userId)		
		REFERENCES user(id)
		ON DELETE CASCADE,
	FOREIGN KEY (postId)		
		REFERENCES post(id)
		ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE favcat (
	userId INT NOT NULL,
	catId INT NOT NULL,
	FOREIGN KEY (userId)		
		REFERENCES user(id)
		ON DELETE CASCADE,
	FOREIGN KEY (catId)		
		REFERENCES category(id)
		ON DELETE CASCADE
) ENGINE=INNODB;





-- SERVER 36:25
